config/routes.rb
Rails.application.routes.draw do
  resources :employees do 
    resources :roles
  end
  delete 'delete_employees', to: 'employees#delete_employees', as: :delete_employees
     
  resources :patients do 
    resources :hospitals
  end
  root 'patients#index'

   resources :users do
     resources :comments
   end
  delete 'delete_users', to: 'users#delete_users', as: :delete_users

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :roles, through: :employee_roles,dependent: :destroy
	has_many :employee_roles
	validates_presence_of :name
	validates :contact_no, presence: true, length: {minimum:10}
	validates :email, presence: true,uniqueness: true , :case_sensitive => false, format: {with:URI::MailTo::EMAIL_REGEXP } 

after_update :display_employee_gender
    def display_employee_gender
    if self.gender.present?
        gender = self.gender
        puts "=====Employee gender is #{gender}====="
    else
    	puts "=====gender cannot be blank====="
      end
    end


before_create :display_employee_name
    def display_employee_name
    if self.name.present?
        name = self.name
        puts "=====Employee name is #{name}====="
    else
    	puts "=====name cannot be blank====="
      end
    end
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :employees, through: :employee_roles
	has_many :employee_roles
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def index
	    if params[:name].present?
        @employees =Employee.eager_load(employee_roles: :role).where("roles.name LIKE ?", "%#{params[:name]}%")
        else
          @employees = Employee.all
    end
	end

	# def index
	# if params[:name].present?
    #   @employees = Employee.joins(:roles).where("roles.name LIKE ?", "%#{params[:name]}%")
    # else
    #   @employees = Employee.all
    # end
	# end

	def new
		@role = Role.all
		@employee = Employee.new

	end

	def create
		@employee = Employee.new(employee_params)
		if @employee.save
				# @employee.roles << Role.where(id: params[:employee][:role_ids])
		redirect_to employee_path(@employee)
	else
		render 'new'
	end
	end

	def show
		@employee = Employee.find(params[:id])
		@role = @employee.roles
	end


	def edit
		@employee = Employee.find(params[:id])
		@role = Role.all
	end

	def update
		@employee = Employee.find(params[:id])
		if @employee.update(employee_params)
			redirect_to employees_path(@employee)
		else
			render "edit"
		end
	end
	
	def destroy
		@employee = Employee.find(params[:id])
		@employee.destroy
		redirect_to employees_path(@employee)
	end

	def delete_employees
        Employee.destroy(params[:employee_ids])
        redirect_to employees_path, notice: "Selected employees have been deleted"
    end
    
	private
	def employee_params
		params.require(:employee).permit(:name,:email,:gender,:contact_no,role_ids:[])
end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for @employee do |f| %>

<% if @employee.errors.any? %>
      <h2>
        <%= pluralize(@employee.errors.count, "error") %>
      </h2>
      <ul>
        <% @employee.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<p>
	<%= f.label :name %>
	<%= f.text_field :name %>
</p>
<p>
	<%= f.label :email %>
	<%= f.text_field :email %>
</p>
<p>
	<%= f.label :gender %>
  <%= f.radio_button :gender, 'Male' %>
  <%= f.label :gender_male, 'Male' %>

  <%= f.radio_button :gender, 'Female' %>
  <%= f.label :gender_female, 'Female' %>

</p>
<p>
	<%= f.label :contact_no %>
	<%= f.text_field :contact_no %>
</p>
<p>
<%= f.label :role_ids, "Select roles" %>
<%= f.collection_select :role_ids, Role.all, :id, :name, {}, { multiple: true } %>
    
<p>
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/employees/edit.html.erb
<%= render 'form' %>
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<%= link_to 'New employee', new_employee_path %>

<%= form_tag employees_path(@employee), method: :get do %>
<%= label_tag :name, "Select:" %>
<%= select_tag :name, options_for_select(Role.select(:name).distinct.order(:name).pluck(:name), params[:name]), include_blank: true %>
<%= submit_tag "Submit" %>
<% end %>

 
<!-- <%= form_tag employees_path, method: :get do %>
  <%= text_field_tag :name, params[:name], placeholder: "Search by Role Name" %>
  <%= submit_tag "Search" %>
<% end %>
<% if @employees.present? %> -->

	<table border="2">
	<tr>
		<th>check</th>
		<th>name</th>
		<th>email</th>
		<th>gender</th>
		<th>contact_no</th>
		<th>roles</th>
		<th colspan="3"></th>
	</tr>

	 <%= form_tag delete_employees_path, method: :delete do %>

	<% @employees.each do |employee| %>

	<td><%= check_box_tag "employee_ids[]", employee.id %></td> 
	<td><%= employee.name %></td>
	<td><%= employee.email %></td>
	<td><%= employee.gender %></td>
	<td><%= employee.contact_no %></td>
	<td>
		<ul>
	<% employee.roles.each do |uc| %>
	<li><%= uc.name %></li>
	<% end %>
</ul>
</td>
	<td><%= link_to 'Edit',edit_employee_path(employee) %></td>
	<td><%= link_to 'Show',employee_path(employee) %></td>
<td><%= link_to 'Destroy', employee_path(employee),method: :delete %></td>
</tr>
<% end %>
<%= submit_tag "Delete selected users:" %>
<% end %>
</table>
<% end %>

app/views/employees/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<h1>Displaying employee details</h1>
<p>
	<strong>name</strong>
	<%= @employee.name %>
</p>
<p>
	<strong>email</strong>
	<%= @employee.email %>
</p>
<p>
	<strong>gender</strong>
	<%= @employee.gender %>
</p>
<p>
	<strong>contact_no</strong>
	<%= @employee.contact_no %>
</p>

  <p>
  	<strong>roles:</strong>
  	<ul>
    <% @role.each do|r| %>
    <li><%= r.name %></li>
    <% end %>
</ul>
  </p>

<%= link_to 'Back',employees_path %>