config/routes.rb
Rails.application.routes.draw do
  resources :employees do 
    resources :roles
  end
  delete 'delete_employees', to: 'employees#delete_employees', as: :delete_employees
     
  resources :patients do 
    resources :hospitals
  end
  root 'patients#index'

   resources :users do
     resources :comments
   end
  delete 'delete_users', to: 'users#delete_users', as: :delete_users

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :name , format: {with: /\A[a-zA-Z]+\z/,message: 'only letters is allowed'}
	validates :phone_no, presence: true, length: {minimum:10}
	validates :email, presence: true,uniqueness: true , :case_sensitive => false, format: {with:URI::MailTo::EMAIL_REGEXP } 
    
    after_delete :display_user_address
    def display_user_address
    if self.address.present?
        address = self.address
        puts "=====User address is #{address}====="
    else
    	puts "=====address cannot be blank====="
      end
    end

    after_update :display_user_gender
    def display_user_gender
    if self.gender.present?
        gender = self.gender
        puts "=====Student gender is #{gender}====="
    else
    	puts "=====gender cannot be blank====="
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	http_basic_authenticate_with name: 'admin', password: 'cnt12345', except: [:index, :show]
  
  def index
   
   @users = User.all
  if params[:search].present?
			@users = User.where("name like?", "%#{params[:search]}%")
		else
			@users = User.all
		end
  end

	def new
		 @user = User.new
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to user_path(@user.id)
		else
			render 'new'
	    end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path(@user)
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to users_path(@user)
		else
			render 'edit'
	    end
    end

  def delete_users
  User.destroy(params[:user_ids])
  redirect_to users_path, notice: "Selected users have been deleted"
end


	private
	def user_params
		
		params.require(:user).permit(:name, :gender, :age, :email, :present_address, :address, :phone_no, :search)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do|f| %>
 
  <% if @user.errors.any? %>
      <h2>
        <%= pluralize(@user.errors.count, "error") %>
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <%end%>
  
<p>
<%= f.label :name%><br>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :gender %><br>
<%= f.text_field :gender %>
</p>
<p>
<%= f.label :age %><br>
<%= f.text_field :age %>
</p>
<p>
<%= f.label :email %><br>
<%= f.text_field :email %>
</p>
<p>
<%= f.label :present_address %><br>
<%= f.text_field :present_address %>
</p>
<p>
<%= f.label :address %><br>
<%= f.text_field :address %>
</p>
<p>
<%= f.label :phone_no %><br>
<%= f.text_field :phone_no %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/users/edit.html.erb
<h1> Edit Article </h1>
<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Displaying the Data</h1>
<%= link_to 'New_user', new_user_path %>

<%= form_tag users_path(@users), method: :get do %>
<%= label_tag :roles, "Select Role" %>
<%= select_tag :roles, options_for_select(Comment.select(:roles).distinct.order(:roles).pluck(:roles), params[:roles]), include_blank: true %>
<%= submit_tag "Submit" %>
<% end %>

 <%= form_tag users_path(@users), method: :get do %>
        <%= label_tag :search, "Search for:" %>
        <%= text_field_tag :search, params[:search]%>
        <%= submit_tag "Search" %>
      <% end %>
<% if params[:search].present? %>

<% if @users.present? %>



<% end %>
<% end %>
<table border="2">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Gender</th>
    <th>Age</th>
    <th>Email</th>
    <th>Present_address</th>
     <th>address</th>
    <th>Phone_no</th>
    <th>Roles</th>
    <th>date_of_birth</th>
  </tr>
  <%= form_tag delete_users_path, method: :delete do %>

  <% @users.each do |user| %>
    <tr>
      <td><%= check_box_tag "user_ids[]", user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.gender %></td>
      <td><%= user.age %></td>
      <td><%= user.email %></td>
      <td><%= user.present_address %></td>
      <td><%= user.address %></td>
      <td><%= user.phone_no %></td>
      <% user.comments.each do|uc| %>
      <td><%= uc.roles %></td>
      <td><%= uc.date_of_birth %></td>
      
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Destroy', user_path(user),
              method: :delete%></td>
    </tr>
    <% end %>
    <% end %>
<%= submit_tag "Delete selected users" %>
<% end %>
</table>

app/views/users/new.html.erb
<h1>New article</h1>
<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>Showing the Data</h1>
<p>
  <strong>name:</strong>
  <%= @user.name %>
</p>
 
<p>
  <strong>gender:</strong>
  <%= @user.gender %>
</p>
<p>
  <strong>age:</strong>
  <%= @user.age %>
</p>
<p>
  <strong>email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>present_address</strong>
  <%= @user.present_address %>
</p>
<p>
  <strong>address</strong>
  <%= @user.address %>
</p>
<p>
  <strong>phone_no</strong>
  <%= @user.phone_no %>
</p>

<%= render @user.comments %>

<%= render 'comments/form' %>

<%= link_to 'Edit', edit_user_path(@user) %>
<%= link_to 'Destroy', user_path(@user), method: :delete %>
<%= link_to 'Back',users_path %>