config/routes.rb
Rails.application.routes.draw do
  resources :employees do 
    resources :roles
  end
  delete 'delete_employees', to: 'employees#delete_employees', as: :delete_employees
     
  resources :patients do 
    resources :hospitals
  end
  root 'patients#index'

   resources :users do
     resources :comments
   end
  delete 'delete_users', to: 'users#delete_users', as: :delete_users

end

app/models/patient.rb
class Patient < ActiveRecord::Base
	 has_many :hospital_patients, dependent: :destroy
     has_many :hospitals, through: :hospital_patients, dependent: :destroy
    
	validates_presence_of :name
	validates :contactno, presence: true, length: {minimum:10}
	validates :email, presence: true,uniqueness: true , :case_sensitive => false, format: {with:URI::MailTo::EMAIL_REGEXP } 

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	def index
		#@patients = Patient.all
		 if params[:search]
      @patients = Patient.joins(:hospitals).where('hospitals.roles LIKE ?', "%#{params[:search]}%")
    else
      @patients = Patient.all
    end
  end
  
	def new
		@patient = Patient.new
	end

	def create
		@patient = Patient.new(patient_params)
		if @patient.save
			@patient.hospitals << Hospital.where(id: params[:patient][:hospital_ids])
			redirect_to patient_path(@patient.id)
		else
			render 'new'
		end
	end

	def show
		@patient = Patient.find(params[:id])
	
	end
	def edit
		@patient = Patient.find(params[:id])
	end
	def update
		@patient = Patient.find(params[:id])
		if @patient.update(patient_params)
			redirect_to patient_path(@patient)
		else
			render 'edit'
		end
	end
	def destroy
		@patient = Patient.find(params[:id])
		@patient.destroy
		redirect_to patients_path(@patient)
	end
		
  private
	def patient_params
		params.require(:patient).permit(:name, :email, :contactno, :gender, :roles, :search ,hospital_id: [])
	end

end





	# def newpatient
	# 	@patient = Patient.new
	# end

	# def savepatient
	# 	@patient = Patient.new(patient_params)
	# 	if @patient.save
	# 		redirect_to patient_path(@patient.id)
	# 	else
	# 		render 'newpatient'
	# 	end
	# end

	# def export
	# 	@patient = Patient.find(params[:id])
	# end

	# def confirm
	# 	@patients = Patient.all
	# end

	# def approve
	# 	@patient = Patient.find(params[:id])
	# end

	# def improve
	# 	@patient = Patient.find(params[:id])
	# 	if @patient.update(patient_params)
	# 		redirect_to patients_path(@patient)
	# 	else
	# 		render 'approve'
	# 	end
	# end

	# def cancel
	# 	@patient = Patient.find(params[:id])
	# 	@patient.destroy
	# 	redirect_to patients_path(@patient)
	# end
	
	

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_child.html.erb
<%= form_tag patients_path do %>
<div>
 <%= label_tag :name, "Name:" %><br>
<%= text_field_tag :name %>
</div>
<div>
<%= label_tag :email, "Email:" %><br>
<%= text_field_tag :email %>
</div>
<div>
<%= label_tag :contactno, "Contactno:" %><br>
<%= text_field_tag :contactno %>
</div>
<div>
<%= label_tag :gender, "Gender:" %><br>
<%= text_field_tag :gender %>
</div>
<div>
  <%= submit_tag "Save" %>
</div>
<% end %>

app/views/patients/_form.html.erb
<% require 'patient_hospital' %>
<%= form_for @patient do |f| %>
<% if @patient.errors.any? %>
<h2>
	<%= pluralize(@patient.errors.count, 'error') %>
</h2>
<ul>
	<% @patient.errors.full_messages .each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>

<p>
<%= f.label :name %>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :email %>
<%= f.text_field :email %>
</p>
<p>
<%= f.label :contactno %>
<%= f.text_field :contactno %>
</p>

<p>
<%= f.label :gender %>
<%= f.text_field :gender %>
</p>
<%= f.label :roles %>
  <%= f.collection_select :hospital_ids, Hospital.all, :id, :roles, {}, { multiple: true } %>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/patients/_search.html.erb
<%= form_for :patient, url: patients_path  do |f| %>
<% if @patient.errors.any? %>
<h2>
	<%= pluralize(@patient.errors.count, 'error') %>
</h2>
<ul>
	<% @patient.errors.full_messages .each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>

<p>
	<%= f.label :name %>
	<%= f.text_field :name %>
</p>
<p>
	<%= f.label :email %>
	<%= f.text_field :email %>
</p>
<p>
	<%= f.label :contactno %>
	<%= f.text_field :contactno %>
</p>
<p>
	<%= f.label :gender %>
	<%= f.text_field :gender %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/patients/approve.html.erb
<h1> Edited Data </h1>
<%= render 'search' %>

app/views/patients/confirm.html.erb
<h1>Displaying all the Patient Details</h1>

<table>
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th>contactno</th>
		<th>Gender</th>
	</tr>

	<% @patients.each do |patient| %>
	<tr>
		<td><%= patient.name %></td>
		<td><%= patient.email %></td>
		<td><%= patient.contactno %></td>
		<td><%= patient.gender %></td>
		<td><%= link_to 'Show', patient_path(patient) %></td>
		<td><%= link_to 'Edit', patient_path(patient) %></td>
		<td><%= link_to 'Destroy', patient_path(patient),
                method: :delete%></td>
    </tr>
		
	</tr>
	<% end %>
</table>

app/views/patients/edit.html.erb
<h1> Edited Data </h1>
<%= render 'form' %>
<%= link_to 'Back', patients_path %>

app/views/patients/export.html.erb
<h1>Showing Data</h1>
<p>
	<strong>name</strong>
	<%= @patient.name %>
</p>
<p>
	<strong>email</strong>
	<%= @patient.email %>
</p>
<p>
	<strong>contactno</strong>
	<%= @patient.contactno %>
</p>
<p>
	<strong>gender</strong>
	<%= @patient.gender %>
</p>
<%= link_to 'Edit', approve_patient_path(@patient) %>

app/views/patients/index.html.erb
<h3>Displaying all the role Detail</h3>

<%= link_to 'New_Patient', new_patient_path %>

  <%= form_tag patients_path(@patients), method: :get do %>
        <%= label_tag :search, "Search for:" %>
        <%= text_field_tag :search, params[:search]%>
        <%= submit_tag "Search" %>
     
	<% if @patients.present? %>
<table>
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th>Contactno</th>
		<th>Gender</th>
		<th>roles</th>
	</tr>

	<% @patients.each do |patient| %>
	<tr>
		<td><%= patient.name %></td>
		<td><%= patient.email %></td>
		<td><%= patient.contactno %></td>
		<td>	<%= patient.gender %></td>
		<td>
			<ul>
		<% patient.hospitals.each do|uc| %>
				<li>
					<%= uc.roles %>
          </li>
          <% end %>
        </ul>
      </td>

		<td><%= link_to 'Edit', edit_patient_path(patient) %></td>
		<td><%= link_to 'Show', patient_path(patient) %></td>
		<td><%= link_to 'Destroy', patient_path(patient),
                method: :delete%></td>
	</tr>
<% end %>
<% end %>
</table>
<% end %>

app/views/patients/new.html.erb
<h1> Patient Data</h1>
<%= render 'form' %>
<%= link_to 'Back', patients_path %>

app/views/patients/newpatient.html.erb
<h1> Patient Data</h1>
<%= render 'search' %>
<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<h1>Showing Data</h1>
<p>
	<strong>Name</strong>
	<%= @patient.name %>
</p>
<p>
	<strong>Email</strong>
	<%= @patient.email %>
</p>
<p>
	<strong>Contactno</strong>
	<%= @patient.contactno %>
</p>
<p>
	<strong>Gender</strong>
	<%= @patient.gender %>
</p>

<p>
	<strong>roles</strong>
</p>

<%= render @patient.hospitals %>

<%= link_to 'Edit', edit_patient_path(@patient) %>
<%= link_to 'Destroy', patient_path(@patient), method: :delete %>
<%= link_to 'Back',patients_path %>